config/routes.rb
ConcertCalendar::Application.routes.draw do
  match 'artists/suggest/' => 'artists#suggest'
  match 'venues/suggest/' => 'venues#suggest'

  resources :concerts
  resources :artists
  resources :venues    

  root :to => 'concerts#index'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  validates :name, :presence => true 
  validates_format_of :website1, :website2, :website3, :with => URI::regexp(%w(http https)), :allow_blank => true
  
  has_and_belongs_to_many :concerts 
  
  def self.search term 
      where("name LIKE ?", "%" + term + "%") 
  end
  
  def self.create_many_artists artist_names
    new_artist_ids = []
    artist_names.each do |a_name|
      artist = self.create( :name => a_name )
      new_artist_ids << artist.id 
    end
    new_artist_ids
  end
end

app/models/concert.rb
# Model for concerts.

class Concert < ActiveRecord::Base
  validates :concert_date, :description, :venue_id, :presence => true
 
  has_and_belongs_to_many :artists
  belongs_to :venue 

  def self.week wnum, ynum
    wstart = Date.commercial( ynum.to_i, wnum.to_i, 1 )
    
    wnum = 0 unless wnum < 52
    wend = Date.commercial( ynum.to_i, wnum.to_i + 1 , 1)
    self.where('concert_date >= ? AND concert_date < ?' , wstart, wend ).order('concert_date')
  end
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  validates :address, :venue_type, :name, :presence => true 
  validates_format_of :website1, :website2, :website3, :with  => URI::regexp(%w(http https)), :allow_blank => true 
  has_many :concerts 
  
  def self.search term 
      result = where("name LIKE ? OR address LIKE ?", "%" + term + "%", "%" + term + "%") 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.order(:name)
  end
  
  def show
    @artist = Artist.find(params[:id])
    @upcoming_concerts = @artist.concerts.where( 'concert_date >= ?', Date.today ).order('concert_date')
  end
  
  def new
    @artist = Artist.new

   end
  
  def create
    @artist = Artist.new(params[:artist])
    
    if @artist.save 
      redirect_to(@artist)
    else
      render :action => "new"
    end
  end
  
  def edit
    @artist = Artist.find(params[:id])
  end
  
  def update
    @artist = Artist.find(params[:id])
    
    if @artist.update_attributes(params[:artist])
      redirect_to @artist
    else
      render :action => "show"
    end
  end
  
  #auto suggest code for Artists
  def suggest
    @result = Artist.search( params[:term] )
    
    respond_to do |format|
        format.html
        format.json { render :json => @result }
    end
  end
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  # Retrieves all Concerts into an array variable and makes it available to the index.html.erb view.
  def index
    if params[:week].blank? 
      @week = Date.today.cweek 
      @year = Date.today.cwyear
    else
      @week = params[:week].to_i
      @year = params[:year].to_i
      
      if @week > 52
        @week = 1 
        @year += 1
      end 
      if @week < 1 
        @week = 52
        @year -= 1
      end
    end
    
    @concerts = Concert.week @week, @year
  end
  
  def show
    @concert = Concert.find(params[:id])
  end
  
  def new
    @concert = Concert.new
  end
  
  def create
    @concert = Concert.new(params[:concert])   
    
    if params[:artist_names].present?
        params[:artist_names].each do |a_name|
          artist = Artist.create( :name => a_name )
          @concert.artists << artist 
        end # /to delete
     end
    
     #to delete
    if @concert.save(params[:concert])
      redirect_to(@concert)
    else
      render :action => 'new'
    end
  end
  
  def edit 
    @concert = Concert.find(params[:id])
  end
  
  def update
    @concert = Concert.find(params[:id])
    
    unless params[:concert][:artist_ids].present?
      params[:concert][:artist_ids] = []
    end
    
    if params[:artist_names].present?        
        params[:concert][:artist_ids] += Artist.create_many_artists( params[:artist_names] )
    end
     
    if @concert.update_attributes params[:concert] 
      redirect_to @concert 
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @concert = Concert.find( params[:id] )
    @concert.destroy 
    
    redirect_to concerts_path
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  def index
    @venues = Venue.order(:venue_type)
  end
  
  def show
    @venue = Venue.find(params[:id])
    @upcoming_concerts = @venue.concerts.where( 'Concerts.concert_date >= ?', Date.today ).order('concert_date')
  end
  
  def new
    @venue = Venue.new
  end
  
  def create
    @venue = Venue.new(params[:venue])
    
    if @venue.save
      redirect_to(@venue)
    else 
      render :action => 'new'
    end
  end
  
  def edit
    @venue = Venue.find(params[:id])
  end
  
  def update
    @venue = Venue.find(params[:id])

    if @venue.update_attributes(params[:venue])
      redirect_to(@venue)
    else
      render :action => 'edit'
    end
  end
  
  def suggest
    @result = Venue.search( params[:term] )
    
    respond_to do |format|
        format.html
        format.json { render :json => @result }
    end
  end
  
  def destroy
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
  def lineup concert
        
  end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do|f| %>

	<div class="field">
		<span class="attr_title"><%= f.label :name %></span>
		<%= f.text_field :name %>
	</div> 

	<div class="field">
		<span class="attr_title"><%= f.label :website %></span>
		<%= f.text_field :website %>
	</div>
	
	<div class="field">
		<span class="attr_title"><%= f.label :biography %></span>
		<%= f.text_area :bio %>
	</div>
	
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/artists/_form.html.haml
= form_for(@artist) do |f|
	.field
		%span.attr_title
			= :name
		= f.text_field :name
	.field
		%span.attr_title
			= :websites
		= f.text_field :website1
		= f.text_field :website2
		= f.text_field :website3
	.field
		%span.attr_title
			= :bio
		= f.text_area :bio 
	.actions
		= f.submit
 

app/views/artists/edit.html.haml
.content
  %h1.red
    Edit
    = @artist.name
 
  = render 'form'

  = link_to 'Back', artists_path, :class => 'red-button'
.sidebar

app/views/artists/index.html.haml
.content
  - @artists.each do |artist|
    .pod
      %a.block-link{:href=> '/artists/' + artist.id.to_s }
        %span.red
          = artist.name
        %br
        = artist.bio

.sidebar
  .pod.red.tan
    %h1.red Artists
    .divider
    This is a directory of all artists that pass through Denver. Did you just start a band or discover one?
  = link_to 'New Artist', new_artist_path, :class => 'red-button'

app/views/artists/new.html.haml
.content
  %h1.red New Artist
 
  = render 'form'

  = link_to 'Back', artists_path, :class => 'red-button'
.sidebar

app/views/artists/show.html.haml
.content
  %h2.red Upcoming Shows
  -if @upcoming_concerts.present?
    = render :partial => 'concerts/clist', :locals => { :concerts => @upcoming_concerts } 
  -else
    This artist does not have any upcoming shows.
.sidebar
  .pod.red.tan
    %h1.red 
      = @artist.name
    .divider
    %h3.red Bio:
    .pod.red.tan.indent
      - if @artist.bio.present?
        = @artist.bio
      - else 
        This artist does not have a bio filled out.
    %h3.red Websites:
    .pod.red.tan.indent
      websites!!!
  = link_to 'Edit', edit_artist_path(@artist.id), :class=>'red-button'

app/views/concerts/_clist.html.haml
- concerts.group_by{|concert| concert.concert_date.to_date}.each do|date, concert|
  .concert-day
    %span.concert_date
      = date.strftime('%b') 
      %br
      = date.strftime('%d')
    = render :partial =>'concerts/concert_stub', :collection => concert, :as => :c

app/views/concerts/_concert.html.haml
.concert_full
	.info_block
		%span.attr_title Description:
		= c.description
	.info_block
		%span.attr_title Lineup:
		%ul.concert_lineup
			- c.artists.each_with_index do |a, index|
				%li
					- i = index
					- while i >= 0 
						&='--'
						- i = i - 1
					= a.name
	
	.info_block
		%span.attr_title Show Info:
		- if c.price.present?
			$ #{c.price} .
		- else 
			FREE!!!
		= link_to '@' + c.venue.name, venue_path(c.venue.id), :class => 'red_link'
		#{c.concert_date.strftime('%I:%M %p')} . #{c.age}
		
	= link_to "Edit", edit_concert_path(c), :class=>"red_button"
	= link_to 'Delete Show', c, :confirm => 'Are you sure?', :method => :delete, :class=>"red_button"
	

app/views/concerts/_concert_stub.html.erb
<div class="concert_stub">
	<a href="/concerts/<%= c.id %>" class="concert_link">
				<div class="info_block">
				<span class="attr_title">Lineup:</span>
				<ul class="concert_lineup">
					<% c.artists.each_with_index do |a, index |%>
						<li>
						<% i = index %>
						<% while i >= 0 %>
							<%= '--' %>
							<% i = i - 1 %>
						<% end %>
						<%= a.name %>
						</li>					
					<%end%>
				</ul>
				</div>
				
				<div class="info_block">
					<span class="attr_title">Show Info:</span>
					<% if c.price != '' %>
						<%= "$" + c.price + ". " %>
					<% else %>
						<%= "$FREE!!!" %>
					<% end %>
					<% if c.venue != nil %>
						<span class="red_link">@<%= c.venue.name %></span>
					<% end %>
					<%= c.concert_date.strftime('%I:%M %p') +". "+ c.age %>
				</div>
	</a>
</div>
	

app/views/concerts/_concert_stub.html.haml
.concert-stub
  %a.block-link{ :href => '/concerts/' + c.id.to_s }
    %ul.lineup
      - c.artists.each_with_index do |a, index|
        %li
          = a.name
    %span.red
      = c.venue.name
    =' @ '
    #{c.concert_date.strftime('%I:%M %p')}. #{c.age}.
    - if c.price.present?
      $ #{c.price} .
    - else 
      FREE!!!
	
	

app/views/concerts/_form.html.erb
	<%= form_for @concert do |f|%>

		<div class="field"> 
			<span class="attr_title"><%= f.label :description %></span>
			<%= f.text_area :description %>
		</div>
	
		<div class="field">
			<span class="attr_title"><%= f.label :show_date %></span>
			<%= f.datetime_select :concert_date %>
		</div>
		
		<div class="field">
			<span class="attr_title"><%= f.label :price %></span>
			$<%= f.text_field :price %>
		</div>

		<div class="field">
			<span class="attr_title"><%= f.label :age %></span>
			<%= f.select :age, options_for_select([	['ALL AGES!!!','ALL AGES!!!'],
													['16+','16+'],
													['18+','18+'],
													['21+','21+'] ])%>
		</div>
		
		<div class="field">
			<span class="attr_title"><%= f.label :lineup %></span>
			
			<div class="suggest_field">
				<input id="artist_autocomplete"/>
				<%= button_tag "Add Artist", :type=>"button", :id=>"add_artist" %>
			</div>
			
			
			<input id="temp_artist" type="hidden" name="tempartist" value=""></input>
			
			<ul class="edit_concert_lineup">
				<% if @concert.artists != '' && @concert.artists != nil %>
					<% @concert.artists.each do |a|%>
						<li><%= a.name %><input type="hidden" name="concert[artist_ids][]" value="<%= a.id %>"></input>
						<%= link_to 'Remove', '#', :class=>'remove_artist red_link' %></li>
					<% end %>
				<% end %>
			</ul>
		</div>
		
		<div class="field">
			<span class="attr_title"><%= f.label :venue %></span>
			
			<input id="temp_venue" type="hidden" name="tempvenue" value=""></input>
			<div id="venue_area">
				<% if @concert.venue != nil %>
					<input type="hidden" name ="concert[venue_id]" value="<%= @concert.venue.id %>"></input>
					<%= @concert.venue.name %><br/>
					<%= button_tag "Change Venue", :type=>"button", :id=>"change_venue"%>
				<% else %>
					<div class="suggest_field">
						<input id="venue_autocomplete"></input>
						<%= button_tag "Select Venue", :type=>"button", :id=>"select_venue" %>
					</div>
				<% end %>
			</div>
		</div>
		
		<div class="actions">
			<%= f.submit  %>
		</div>
	<% end %>

app/views/concerts/_form.html.haml
= form_for @concert do |f| 
  %fieldset 
    %legend.red Show Info
    .field
      %legend.red Description *
      = f.text_area :description
    .field
      %legend.red Show Date *
      = f.datetime_select :concert_date, :ampm => true, :minute_step => 15
    .field
      %legend.red Price( $ )
      = f.text_field :price
    .field
      %legend.red Age 
      = f.text_field :age
  %fieldset
    %legend.red Lineup * 
    .field
      %input#artist_autocomplete
      %ul.lineup
        - if :artist_ids.present?
          - @concert.artists.each do |artist|
            %li
              = artist.name
              %input{ :type=>'hidden', :name=>'concert[artist_ids][]',:value=>artist.id }
              = link_to 'Remove', '#', :class=>'remove_artist red-button'	
  %fieldset	
    %legend.red Venue *
    .field
      %input#venue_autocomplete
      -if @concert.venue.present? 
        %input{ :type=>'hidden', :name=>'concert[venue_id]', :value=>@concert.venue.id }
        = @concert.venue.name
    #venue_area
    #new_artist_form{ :title => 'New Artist'}
      New artist form here.
  .actions
    = f.submit 'Create'
		

app/views/concerts/edit.html.haml
.content
  %h1.red Edit Show

  = render 'form'

  = link_to 'Back', concerts_path, :class => 'red-button'
.sidebar

app/views/concerts/index.html.erb
<h1 class="page_title">The Freakin' Week</h1>
<div id="week_head">
	<%= link_to '>', concerts_path(:week => @week + 1, :year => @year), :class =>'nav_arrow_right'%>
	<h2 id="week_headline"><%= Date.commercial( @year, @week, 1 ) %> - <%= Date.commercial( @year, @week, 7 ) %></h2>
	<%= link_to '<', concerts_path(:week => @week - 1, :year => @year ), :class =>'nav_arrow_left'%>	
</div>

<% if @concerts.present? %>
	<% @concerts.group_by{|concert| concert.concert_date.to_date}.each do|date, concert|%>
		<span class="concert_date"><%= date.strftime('%A, %B %d') %></span>
		
			<%= render :partial => 'concert_stub', :collection => concert, :as => :c  %>
		
	<% end %>
<% else %>
	<span class="big_text center">There are no shows logged for this week</span>
<% end %>

<%= link_to 'New Concert', new_concert_path, :class => 'red_button' %>

app/views/concerts/index.html.haml
.content
  %h2.red The Freakin' Week: #{Date.commercial( @year, @week, 1 ).strftime('%m.%d.%y')} - #{Date.commercial( @year, @week, 7 ).strftime('%m.%d.%y')}

  - if @concerts.present?
    = render :partial => 'clist', :locals => { :concerts => @concerts }
  - else 
    There are now shows logged for this week
  = link_to 'Previous', concerts_path(:week => @week - 1, :year => @year ), :class => 'left red-button'
  = link_to 'Next', concerts_path(:week => @week + 1, :year => @year), :class => 'right red-button'
  
.sidebar
  .pod.red.left.tan
    %h1.red Show Calendar
    .divider
    Welcome to the Howl Denver calendar! This lists local shows happening all over Denver. Know of a show but don't see it on the calendar?
  = link_to 'New Concert', new_concert_path, :class => 'red-button' 

app/views/concerts/new.html.haml
.content
  %h1.red New Show

  = render 'form'

  = link_to 'Back', concerts_path, :class => 'red-button'
.sidebar

app/views/concerts/show.html.erb
	<span class="concert_date"><%= @concert.concert_date.strftime('%A, %B %d') %></span>
	
	<% #render the concert partial %>
	<%= render :partial => @concert, :as => :c %>
	

app/views/concerts/show.html.haml
.content
  %span.concert_date
    = @concert.concert_date.strftime('%b') 
    %br
    = @concert.concert_date.strftime('%d')
  .pod.concert-stub
    %h2.red Lineup:
    %ul.lineup
      -@concert.artists.each do |artist|
        %li
          %a.block-link{ :href => '/artists/' + artist.id.to_s }
            =artist.name 
            .pod.red
              =artist.bio   
  %a.block-link{ :href=> '/venues/' + @concert.venue.id.to_s }
    %h2.red @ #{@concert.venue.name}
    .pod
      %span.red
        =@concert.venue.address
      %br
      %br
      =@concert.venue.description
    
.sidebar
  .pod.red.tan
    %h2.red Description
    .divider
    = @concert.description
    %h2.red Show Info
    .divider
    %span.left Time:
    %span.right
      = @concert.concert_date.strftime('%I:%M %p')
    %br
    %span.left Age:
    %span.right
      = @concert.age 
    %br
    %span.left Cost:
    %span.right
      - if @concert.price.present?
        $ #{@concert.price}
      - else 
        Free
        
  = link_to 'Edit', edit_concert_path( @concert.id ), :class => 'red-button'

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Howl Denver
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.js" 
    = javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.js"
    
    = csrf_meta_tags 
  %body
    #wrapper
      #header
        .fh-container  
          = link_to '', root_path, :id =>'logo'
          %ul.navigation
            %li 
              = link_to 'Calendar', concerts_path
            %li 
              = link_to 'Artists', artists_path
            %li 
              = link_to 'Venues', venues_path
      .container
        = yield
      .push
    #footer
      .fh-container
        %ul.navigation
          %li 
            = link_to 'Calendar', concerts_path
          %li 
            = link_to 'Artists', artists_path
          %li 
            = link_to 'Venues', venues_path

app/views/venues/_form.html.erb
<%= form_for(@venue) do |f| %>
	<div class="field">
		<span class="attr_title"><%= f.label :name %></span>
		<%= f.text_field :name %>
	</div>
	
	<div class="field">
		<span class="attr_title"><%= f.label :address %></span>
		<%= f.text_field :address %>
	</div>

	<div class="field">
		<span class="attr_title"><%= f.label :venue_type %></span>
		<%= f.select :venue_type, options_for_select([	['Warehouse','Warehouse'],
														['Bar','Bar'],
														['Venue','Venue'],
														['Cafe','Cafe'],
														['House','House'] ] ) %>
	</div>

	<div class="field">
		<span class="attr_title"><%= f.label :phone %></span>
		<%= f.text_field :phone %>
	</div>

	<div class="field">
		<span class="attr_title"><%= f.label :email %></span>
		<%= f.text_field :email %>
	</div>

	<div class="field">
		<span class="attr_title"><%= f.label :website %></span>
		<%= f.text_field :website %>
	</div>

	<div class="field">
		<span class="attr_title"><%= f.label :description %></span>
		<%= f.text_area :description %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>	
<% end %>

app/views/venues/_form.html.haml
= form_for @venue do |f|
  .field
    %span.attr_title 
      = f.label :name
    = f.text_field :name
  .field
    %span.attr_title 
      = f.label :address
    = f.text_field :address
  .field
    %span.attr_title 
      = f.label :venue_type
    = f.select :venue_type, options_for_select([	['Warehouse','Warehouse'],
														['Bar','Bar'],
														['Venue','Venue'],
														['Cafe','Cafe'],
														['House','House'] ] )
  .field
    %span.attr_title 
      = f.label :websites
    = f.text_field :website1
    = f.text_field :website2
    = f.text_field :website3
  .field
    %span.attr_title 
      = f.label :description
    = f.text_area :description
  .actions
    =f.submit

app/views/venues/edit.html.erb
<h1 class="page_title">Edit <%= @venue.name %></h1>

<%= render 'form'%>

<%= link_to 'Back', venues_path, :class=>"red_button" %>

app/views/venues/edit.html.haml
.content
  %h1.red 
  Edit
  = @venue.name

  = render 'form'

  = link_to 'Back', venues_path, :class=>'red-button'
.sidebar

app/views/venues/index.html.erb
<h1 class="page_title">Venues</h1>

<% @venues.group_by{ |venue| venue.venue_type }.each do |venue_type, venues| %>
	<span class="venue_type"><%= venue_type %></span>
	
	<% venues.each do |venue| %>
		<div class="venue_stub">
			<%= link_to venue.name, venue_path(venue.id), :class=>"attr_title" %>
			<%= venue.address %>
		</div>
	<% end %>
	
<% end %>

<br/>
<%= link_to "New Venue", new_venue_path, :class => "red_button" %>

app/views/venues/index.html.haml
.content
  - @venues.group_by{ |venue| venue.venue_type }.each do |venue_type, venues| 
    %span.venue-type
      = venue_type + 's'
    - venues.each do |venue|
      .pod
        %a.block-link{ :href => '/venues/' + venue.id.to_s }
          %span.red
            = venue.name
          %br
          = venue.address
.sidebar
  .pod.red.tan
    %h1.red Venues
    .divider
    This is a list of venues in the Denver area. Did you find a new spot no one else knows about?
  = link_to 'New Venue', new_venue_path, :class => "red-button"

app/views/venues/new.html.erb
<h1 class="page_title">New Venue</h1>

<%= render 'form'%>

<%= link_to 'Back', venues_path, :class=>"red_button" %>

app/views/venues/new.html.haml
.content
  %h1.red New Venue

  = render 'form'

  = link_to 'Back', venues_path, :class=>'red-button'
.sidebar

app/views/venues/show.html.haml
.content
  %h2.red Upcoming Shows
  -if @upcoming_concerts.present?
    = render :partial => 'concerts/clist', :locals => { :concerts => @upcoming_concerts } 
  -else
    This venue does not have any upcoming shows.
.sidebar
  .pod.red.tan
    %h1.red
      = @venue.name
    .divider
    %h3.red Description:
    .pod.red.tan.indent
      -if @venue.description.present?
        = @venue.description
      -else 
        This venue does not have a description filled out.
    %h3.red Address:
    .pod.red.tan.indent
      = @venue.address
    %h3.red Websites:
    .pod.red.tan.indent
      websites!
  = link_to 'Edit', edit_venue_path(@venue.id), :class=>'red-button'